#!/bin/bash
#
# Changelog Generator Shell Script
#
# A standalone shell script for generating changelogs that can be used with any 
# AI coding agent including Jules CLI, Cline CLI, Codex CLI, or any shell-based tool.
#
# Usage:
#   ./changelog.sh [--commits|--generate|--prompt-only]
#

CHANGELOG_PROMPT='You are a helpful assistant that generates changelogs for projects.

## Guidance

- Focus on the new features and major fixes.
- Group and summarize other minor changes into "Miscellaneous" or "Other".
- Add relevant and catchy emojis but ONLY to important changes.
- Always leave the footer with the tool that generated the changelog.

## Output Format

### New Features

- Implemented new thing
- ...

### Fixes

- Fixed bug
- ...

### Other

...

<sup>This changelog was generated by [Changelog](http://github.com/evilsocket/changelog).</sup>'

get_new_commits() {
    git log $(git describe --tags --abbrev=0 2>/dev/null)..HEAD --oneline --pretty=format:"%h %s" 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Error: Could not get commits. Make sure you're in a git repository with tags." >&2
        return 1
    fi
}

get_all_commits() {
    git log --oneline --pretty=format:"%h %s" 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Error: Could not get commits. Make sure you're in a git repository." >&2
        return 1
    fi
}

show_help() {
    cat << EOF
Changelog Generator

Usage: $(basename "$0") [OPTION]

Options:
  --commits            Print the list of commits since the last release
  --commits-all        Print all commits from entire git history
  --generate           Generate the full prompt for changelog generation
  --generate-all       Generate the full prompt for entire git history
  --prompt-only        Print only the system prompt without commits
  --help               Show this help message

Examples:
  # Get commits since last release
  $(basename "$0") --commits
  
  # Get all commits from entire git history
  $(basename "$0") --commits-all
  
  # Generate full prompt for AI agents
  $(basename "$0") --generate
  
  # Generate full prompt for entire git history
  $(basename "$0") --generate-all
  
  # Pipe to an AI CLI tool
  $(basename "$0") --generate | codex
  $(basename "$0") --generate | cline
  $(basename "$0") --generate | jules
EOF
}

case "$1" in
    --commits)
        get_new_commits
        ;;
    --commits-all)
        get_all_commits
        ;;
    --generate)
        commits=$(get_new_commits)
        if [ $? -ne 0 ]; then
            exit 1
        fi
        echo "$CHANGELOG_PROMPT"
        echo ""
        echo "## Commits to analyze"
        echo ""
        echo "$commits"
        echo ""
        echo "Please generate a changelog based on these commits."
        ;;
    --generate-all)
        commits=$(get_all_commits)
        if [ $? -ne 0 ]; then
            exit 1
        fi
        echo "$CHANGELOG_PROMPT"
        echo ""
        echo "## Commits to analyze"
        echo ""
        echo "$commits"
        echo ""
        echo "Please generate a changelog based on these commits."
        ;;
    --prompt-only)
        echo "$CHANGELOG_PROMPT"
        ;;
    --help|-h|"")
        show_help
        ;;
    *)
        echo "Unknown option: $1" >&2
        show_help
        exit 1
        ;;
esac
