#!/usr/bin/env python3
"""
Changelog CLI Tool

A standalone CLI tool for generating changelogs that can be used with any AI coding agent
including Jules CLI, Cline CLI, Codex CLI, or any other CLI-based agent.

Usage:
    python changelog_cli.py [--commits] [--generate]
"""

import argparse
import subprocess
import sys


CHANGELOG_PROMPT = """You are a helpful assistant that generates changelogs for projects.

## Guidance

- Focus on the new features and major fixes.
- Group and summarize other minor changes into "Miscellaneous" or "Other".
- Add relevant and catchy emojis but ONLY to important changes.
- Always leave the footer with the tool that generated the changelog.

## Output Format

### New Features

- Implemented new thing
- ...

### Fixes

- Fixed bug
- ...

### Other

...

<sup>This changelog was generated by [Changelog](http://github.com/evilsocket/changelog).</sup>
"""


def get_new_commits() -> str:
    """Get the list of new commits since the last release."""
    try:
        result = subprocess.run(
            'git log $(git describe --tags --abbrev=0)..HEAD --oneline --pretty=format:"%h %s"',
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            return result.stdout
        return f"Error getting commits: {result.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"


def get_full_prompt(commits: str) -> str:
    """Generate the full prompt for changelog generation."""
    return f"""{CHANGELOG_PROMPT}

## Commits to analyze

{commits}

Please generate a changelog based on these commits."""


def main():
    parser = argparse.ArgumentParser(
        description="Generate changelogs for git repositories",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Get commits since last release
    python changelog_cli.py --commits
    
    # Generate full prompt for AI agents
    python changelog_cli.py --generate
    
    # Pipe to an AI CLI tool
    python changelog_cli.py --generate | codex
    python changelog_cli.py --generate | cline
        """
    )
    
    parser.add_argument(
        "--commits",
        action="store_true",
        help="Print the list of commits since the last release"
    )
    
    parser.add_argument(
        "--generate",
        action="store_true", 
        help="Generate the full prompt for changelog generation"
    )
    
    parser.add_argument(
        "--prompt-only",
        action="store_true",
        help="Print only the system prompt without commits"
    )
    
    args = parser.parse_args()
    
    if args.prompt_only:
        print(CHANGELOG_PROMPT)
        return 0
    
    if args.commits:
        commits = get_new_commits()
        print(commits)
        return 0
        
    if args.generate:
        commits = get_new_commits()
        if commits.startswith("Error"):
            print(commits, file=sys.stderr)
            return 1
        print(get_full_prompt(commits))
        return 0
    
    # Default: show help
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
