"""
Changelog Agent for LangChain

This agent generates changelogs for git repositories using LangChain.
It analyzes commits since the last release and creates a nicely formatted markdown changelog.
"""

import subprocess
from typing import Optional

from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.tools import tool
from langchain_core.prompts import ChatPromptTemplate


SYSTEM_PROMPT = """You are a helpful assistant that generates changelogs for projects.

## Guidance

- Use the get_new_commits tool to get the list of commits if not provided.
- Use the create_changelog tool to generate a changelog for the new commits.
- Focus on the new features and major fixes.
- Group and summarize other minor changes into "Miscellaneous" or "Other".
- Add relevant and catchy emojis but ONLY to important changes.
- Always leave the footer with the tool that generated the changelog."""


@tool
def get_new_commits() -> str:
    """Get the list of new commits since the last release."""
    try:
        result = subprocess.run(
            'git log $(git describe --tags --abbrev=0)..HEAD --oneline --pretty=format:"%h %s"',
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            return result.stdout
        return f"Error getting commits: {result.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"


@tool
def create_changelog(markdown: str) -> str:
    """Create a changelog for the new commits.
    
    Args:
        markdown: The changelog markdown content.
        
    Example format:
        ### New Features
        
        - Implemented new thing
        - ...
        
        ### Fixes
        
        - Fixed bug
        - ...
        
        ### Other
        
        ...
        
        <sup>This changelog was generated by [Changelog](http://github.com/evilsocket/changelog).</sup>
    """
    print(markdown)
    return markdown


def create_changelog_agent(llm):
    """Create a changelog agent using the provided LLM.
    
    Args:
        llm: A LangChain chat model (e.g., ChatOpenAI, ChatAnthropic, etc.)
        
    Returns:
        AgentExecutor: The configured changelog agent
        
    Example:
        from langchain_openai import ChatOpenAI
        
        llm = ChatOpenAI(model="gpt-4")
        agent = create_changelog_agent(llm)
        result = agent.invoke({"input": "Generate a changelog for this repository"})
    """
    tools = [get_new_commits, create_changelog]
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ])
    
    agent = create_tool_calling_agent(llm, tools, prompt)
    
    return AgentExecutor(agent=agent, tools=tools, verbose=True)


def run_changelog_agent(llm, commits: Optional[str] = None):
    """Run the changelog agent to generate a changelog.
    
    Args:
        llm: A LangChain chat model
        commits: Optional pre-fetched commits. If not provided, the agent will fetch them.
        
    Returns:
        str: The generated changelog markdown
    """
    agent = create_changelog_agent(llm)
    
    if commits:
        input_text = f"Generate a changelog for these commits:\n\n{commits}"
    else:
        input_text = "Get the new commits and generate a changelog for this repository"
    
    result = agent.invoke({"input": input_text})
    return result["output"]


if __name__ == "__main__":
    # Example usage with OpenAI
    try:
        from langchain_openai import ChatOpenAI
        
        llm = ChatOpenAI(model="gpt-4")
        changelog = run_changelog_agent(llm)
        print(changelog)
    except ImportError:
        print("Please install langchain-openai: pip install langchain-openai")
    except Exception as e:
        print(f"Error: {e}")
