"""
Changelog Agent for OpenAI Agents SDK

This agent generates changelogs for git repositories using OpenAI Agents.
It analyzes commits since the last release and creates a nicely formatted markdown changelog.
"""

import subprocess
from typing import Optional

from agents import Agent, Runner, function_tool


INSTRUCTIONS = """You are a helpful assistant that generates changelogs for projects.

## Guidance

- Use the get_new_commits tool to get the list of commits since the last release if not provided.
- Use the get_all_commits tool to get all commits from the entire git history for retroactive changelog generation.
- Use the create_changelog tool to generate a changelog for the commits.
- Focus on the new features and major fixes.
- Group and summarize other minor changes into "Miscellaneous" or "Other".
- Add relevant and catchy emojis but ONLY to important changes.
- Always leave the footer with the tool that generated the changelog."""


@function_tool
def get_new_commits() -> str:
    """Get the list of new commits since the last release."""
    try:
        result = subprocess.run(
            'git log $(git describe --tags --abbrev=0)..HEAD --oneline --pretty=format:"%h %s"',
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            return result.stdout
        return f"Error getting commits: {result.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"


@function_tool
def get_all_commits() -> str:
    """Get all commits from the entire git history for retroactive changelog generation."""
    try:
        result = subprocess.run(
            'git log --oneline --pretty=format:"%h %s"',
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            return result.stdout
        return f"Error getting commits: {result.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"


@function_tool
def create_changelog(markdown: str) -> str:
    """Create a changelog for the new commits.
    
    Args:
        markdown: The changelog markdown content.
        
    Example format:
        ### New Features
        
        - Implemented new thing
        - ...
        
        ### Fixes
        
        - Fixed bug
        - ...
        
        ### Other
        
        ...
        
        <sup>This changelog was generated by [Changelog](http://github.com/evilsocket/changelog).</sup>
    """
    print(markdown)
    return markdown


def create_changelog_agent(model: str = "gpt-4o") -> Agent:
    """Create a changelog agent.
    
    Args:
        model: The OpenAI model to use (default: gpt-4o)
        
    Returns:
        Agent: The configured changelog agent
        
    Example:
        agent = create_changelog_agent()
        result = Runner.run_sync(agent, "Generate a changelog for this repository")
    """
    return Agent(
        name="ChangelogAgent",
        instructions=INSTRUCTIONS,
        tools=[get_new_commits, get_all_commits, create_changelog],
        model=model,
    )


async def run_changelog_agent_async(
    commits: Optional[str] = None, 
    model: str = "gpt-4o",
    full_history: bool = False
) -> str:
    """Run the changelog agent asynchronously.
    
    Args:
        commits: Optional pre-fetched commits. If not provided, the agent will fetch them.
        model: The OpenAI model to use
        full_history: If True, generate changelog for the entire git history.
                     If False (default), only include commits since the last release.
        
    Returns:
        str: The generated changelog markdown
    """
    agent = create_changelog_agent(model)
    
    if commits:
        input_text = f"Generate a changelog for these commits:\n\n{commits}"
    elif full_history:
        input_text = "Get all commits from the entire git history and generate a comprehensive changelog for this repository"
    else:
        input_text = "Get the new commits and generate a changelog for this repository"
    
    result = await Runner.run(agent, input_text)
    return result.final_output


def run_changelog_agent(
    commits: Optional[str] = None, 
    model: str = "gpt-4o",
    full_history: bool = False
) -> str:
    """Run the changelog agent synchronously.
    
    Args:
        commits: Optional pre-fetched commits. If not provided, the agent will fetch them.
        model: The OpenAI model to use
        full_history: If True, generate changelog for the entire git history.
                     If False (default), only include commits since the last release.
        
    Returns:
        str: The generated changelog markdown
    """
    agent = create_changelog_agent(model)
    
    if commits:
        input_text = f"Generate a changelog for these commits:\n\n{commits}"
    elif full_history:
        input_text = "Get all commits from the entire git history and generate a comprehensive changelog for this repository"
    else:
        input_text = "Get the new commits and generate a changelog for this repository"
    
    result = Runner.run_sync(agent, input_text)
    return result.final_output


if __name__ == "__main__":
    # Example usage
    try:
        changelog = run_changelog_agent()
        print(changelog)
    except ImportError:
        print("Please install openai-agents: pip install openai-agents")
    except Exception as e:
        print(f"Error: {e}")
